"""Stage 4 — Recommendation.

    data/analyses/<slug>.json  ->  memos/<slug>.md

Renders the one-page memo. Deterministic templating, no model call: the
judgement was made and scored in stage 3, and this stage only lays it out. That
keeps a memo from ever disagreeing with the score it came from, and makes fixing
a formatting problem free.

The bar the brief sets is that a partner understands the call in 60 seconds, so
the call and the reason for it sit above everything else. Supporting detail is
ordered by how likely a partner is to want it next, and every factual section
ends at a list of sources they can open.
"""

from __future__ import annotations

from pathlib import Path

from pipeline import thesis
from pipeline.models import Analysis

INPUT_DIR = Path("data/analyses")
OUTPUT_DIR = Path("memos")

# Ordered worst-first so the reasons a company lost points are read before the
# reasons it kept them — which is the order a partner argues with.
_CALL_EMOJI = {"Take a meeting": "🟢", "Watch": "🟡", "Pass": "🔴"}


def _headline(a: Analysis) -> list[str]:
    website = a.candidate.website
    site = f"[{website.replace('https://', '').rstrip('/')}]({website})" if website else "no website found"
    batch = next(
        (s.label for s in a.candidate.signals_of("freshness") if "batch" in s.label.lower()),
        None,
    )
    facts = [site] + ([batch] if batch else [])

    return [
        f"# {a.name} — {a.call}",
        "",
        f"**{a.score}/100** against [the thesis](../docs/thesis.md) · "
        f"{a.coverage:.0%} evidence coverage · {' · '.join(facts)}",
        "",
        f"> {a.candidate.one_liner}" if a.candidate.one_liner else "",
        "",
        f"## {_CALL_EMOJI.get(a.call, '')} {a.call}",
        "",
        a.call_reason,
        "",
    ]


def _scores_table(a: Analysis) -> list[str]:
    rows = [
        "| Component | Score | Reasoning |",
        "|---|---:|---|",
    ]
    for component in thesis.COMPONENTS:
        judged = a.component(component.id)
        if not judged:
            continue
        rationale = judged.rationale.replace("|", "\\|")
        if not judged.observed:
            rationale = f"*No evidence found; scored at the neutral band.* {rationale}"
        rows.append(f"| {component.name} | {judged.score}/{component.weight} | {rationale} |")
    rows += ["", f"**Total: {a.score}/100**", ""]
    return rows


def _sources(a: Analysis) -> list[str]:
    """Every page the evidence behind this memo came from.

    Deliberately the *evidence* provenance rather than the candidate's — a
    reader checking a claim about the founders needs the YC page the bio came
    from, not the search result that surfaced the company.
    """
    seen: dict[str, str] = {}
    for prov in [*a.sources, *a.candidate.provenance]:
        seen.setdefault(prov.url, prov.source)
    lines = ["## Sources", "", "Every claim above traces to one of these pages.", ""]
    lines += [f"- `{source}` — [{url}]({url})" for url, source in seen.items()]
    return lines + [""]


def render(a: Analysis) -> str:
    parts: list[str] = _headline(a)

    parts += ["## What they do", "", a.product, ""]
    parts += ["## Team", "", a.team, ""]
    parts += ["## Market", "", a.market, ""]

    parts += ["## Score against the thesis", ""]
    parts += _scores_table(a)

    if a.risks:
        parts += ["## Risks", ""] + [f"- {r}" for r in a.risks] + [""]

    if a.open_questions:
        parts += ["## Open questions", ""] + [f"- {q}" for q in a.open_questions] + [""]

    if a.what_would_change_my_mind:
        parts += ["## What would change our mind", ""]
        parts += [f"{i}. {t}" for i, t in enumerate(a.what_would_change_my_mind, 1)]
        parts += [""]

    if a.gaps:
        # Printed, not hidden. A partner deciding how much to trust this memo
        # needs to know what the research pass could not find.
        parts += ["## What we could not find", ""] + [f"- {g}" for g in a.gaps] + [""]

    if a.uncited_refs:
        parts += [
            "## ⚠ Unverified references",
            "",
            "The analysis cited these, and they do not match any evidence item "
            "gathered for this company. Treat any claim resting on them as unsourced.",
            "",
        ] + [f"- {r}" for r in a.uncited_refs] + [""]

    parts += _sources(a)
    parts += [
        "---",
        "",
        f"*Generated by [ideascraper](../README.md) from evidence gathered "
        f"{a.generated_at:%d %b %Y}. Scored by `{a.model}` against the components "
        f"in [docs/thesis.md](../docs/thesis.md); the total, the coverage figure "
        f"and this call were computed from those scores, not chosen by the model.*",
        "",
    ]
    return "\n".join(line for line in parts if line is not None)


def render_index(analyses: list[Analysis]) -> str:
    """A single page a partner can skim before opening anything."""
    gate = thesis.BY_ID[thesis.GATE_COMPONENT]
    ranked = sorted(analyses, key=lambda a: -a.score)
    lines = [
        "# Pipeline output",
        "",
        f"{len(ranked)} companies scored against [the thesis](../docs/thesis.md).",
        "",
        f"| | Company | Score | Thesis fit | Coverage | Call |",
        "|---|---|---:|---:|---:|---|",
    ]
    for a in ranked:
        judged = a.component(thesis.GATE_COMPONENT)
        fit = f"{judged.score}/{gate.weight}" if judged else "—"
        lines.append(
            f"| {_CALL_EMOJI.get(a.call, '')} | [{a.name}]({a.slug}.md) | "
            f"{a.score}/100 | {fit} | {a.coverage:.0%} | **{a.call}** |"
        )

    passes = sum(1 for a in ranked if a.call == "Pass")
    lines += [
        "",
        f"**Read the ordering by 'thesis fit', not by score.** That column is "
        f"*{gate.name.lower()}* — can a reader name what stops being paid for. Below "
        f"{thesis.GATE_MINIMUM}/{gate.weight} the call is a Pass whatever the total, "
        "which is why a company can score higher overall than one above it and still "
        "be declined. A strong team building something this fund does not back is "
        "still something this fund does not back.",
        "",
        f"{passes} of {len(ranked)} are a Pass. That is the thesis working: it backs "
        "companies taking over spend an SMB already has, and most of what a search "
        "for AI agents surfaces is developer tooling, which it declines on purpose.",
        "",
    ]
    return "\n".join(lines)


def run(*, input_dir: Path = INPUT_DIR, output_dir: Path = OUTPUT_DIR) -> list[Analysis]:
    paths = sorted(input_dir.glob("*.json"))
    if not paths:
        raise FileNotFoundError(
            f"no analyses in {input_dir} — run `python -m pipeline analyze` first"
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    analyses = [Analysis.model_validate_json(p.read_text()) for p in paths]

    for analysis in analyses:
        (output_dir / f"{analysis.slug}.md").write_text(render(analysis))
        print(f"{analysis.name:26.26} {analysis.call:<15} memos/{analysis.slug}.md")

    (output_dir / "index.md").write_text(render_index(analyses))
    return analyses
